### ISSUE TITLE
Extend file protocol to support filtering based on file meta-data

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#1739]
Extend #1578 to support identification of vulnerable components within archives, based on their hashes.

Features required to support this:
* [ ] be able to filter file based on their meta-data:
  * [ ] file name (e.g. `vulnerable-v1.2.3.jar`)
  * [ ] (optional) other info like date created/modified or EXIF meta-data etc.
  * [ ] hash:
    * [ ] sha1
    * [ ] sha256
    * [ ] md5
* [ ] be able to match content of filtered files (e.g. files within a matched archive)
  
Example use-cases:
* combined with a list of vulnerable libraries (name + version / filename) or vulnerable hashes (e.g. https://github.com/mubix/CVE-2021-44228-Log4Shell-Hashes), we can generate a template that could identify vulnerable components within `WAR`,  `EAR` or other archive files.
* filter on files matching the `log4j.*?\.jar` regex, then check if a certain condition is met within the file content (e.g. any `.class` file contains the word "JNDI")

**Comment by dogancanbakir** [comment]
Closing this issue due to prolonged inactivity. Please reopen if you think this is still relevant or requires further discussion.
