### ISSUE TITLE
Extend the clustering support

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2438]
Protocols:
- [x] [DNS](https://github.com/projectdiscovery/nuclei/issues/2439) https://github.com/projectdiscovery/nuclei/issues/2439
- [x] [TLS](https://github.com/projectdiscovery/nuclei/issues/2440) https://github.com/projectdiscovery/nuclei/issues/2440
- [x] ~[File](https://github.com/projectdiscovery/nuclei/issues/2441)~ (not planned)
