### ISSUE TITLE
Add support to additional network protocols

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#2699]
### Please describe your feature request:

Cover a wide range of network protocols described in the below links - 

- https://github.com/praetorian-inc/fingerprintx/tree/main/pkg/plugins/services
- https://book.hacktricks.xyz/network-services-pentesting/pentesting-jdwp-java-debug-wire-protocol (Pentesting network services)
- https://github.com/lcvvvv/kscan/tree/master/lib

### Describe the use case of this feature:

Allowing templates to cover more and more network services + making them easily extensible and modular for users.

**Comment by Ice3man543** [comment]
TODO Items -

- [ ] Cover password bruteforce for known network protocols
- [ ] Cover information gathernig for known network protocols
- [ ] Cover additional implementations of network protocols subset
- [ ] Cover struct-pack type python script for network exploits (utilise nebula or something similar)
