### ISSUE TITLE
Extended Memory Usage Optimizations

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4703]
### Please describe your feature request:

 context #4680 . it was observed from testing that following changes need to be done to address allocations / peak memory usage 

```[tasklist]
### Tasks
- [ ] Implement a immutable copy of bytes.buffer to avoid allocation when doing .String() and allow segmentation to consolidate body and full response into single byte array
- [ ] Investigate need of deepcopier in fastdialer ( observed in cpu profiles)
- [ ] Experiment: client side caching of response body when response header contains `etag` or other known headers . this will reduce memory usage by reusing immutable response bodies ( when scanning a target which is serving 404 or content from s3 bucket etc)
- [ ] Using Javascript Runtime instead of projectdiscovery/dsl , design helper functions to accept both []byte slice or io.Reader to avoid unnecessary allocations
- [ ] Refactor to make Executers stateless and move state to scan.ScanContext
```
