### ISSUE TITLE
Complete support for Auth Protected Targets

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4793]
Current Nuclei Support is limited to global headers but we will be need a more granular per Host/Target credentials as well as support for login to achieve easy scanning behind authenticated targets

At high level this support can be split into 3 groups
1) Static Auth
       This would include supporting target specific creds and all static authentication methods ( aka that don't actually include the login process) ex: api-keys , authorization header token , www-Authenticate etc

2) Dynamic Auth
       This would include supporting logic sequence and retrieving appropriate tokens / cookies and refereshng tokens that have a time limit

3) Integrations
       Easy integrations to stores like Hashicorp Vault , 1password etc

```[tasklist]
### Tasks
- [ ] https://github.com/projectdiscovery/nuclei/issues/4794
- [ ] https://github.com/projectdiscovery/nuclei/issues/4845
- [ ] 1password Integration
- [ ]  Hashicorp Vault Integration
``` 

>[!NOTE]
> Some tasks are inter-dependent ex: dynamic auth needs static auth to already exist . and integrations require implementation of static auth first
