### ISSUE TITLE
Nuclei Fuzzing Improvements ( Scanning for Unknown Vulnerabilities)

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4795]
### Please describe your feature request:
Nuclei currently excels and writing checks/exploits for existing CVEs , detection templates etc .
Below Features are required in nuclei for writing fuzzing templates

```[tasklist]
### Tasks
- [ ] https://github.com/projectdiscovery/nuclei/issues/4131
- [ ] https://github.com/projectdiscovery/nuclei/issues/4113
- [ ] https://github.com/projectdiscovery/nuclei/issues/3952
- [ ] https://github.com/projectdiscovery/nuclei/issues/4844
- [ ] https://github.com/projectdiscovery/nuclei/issues/4794
- [ ] https://github.com/projectdiscovery/nuclei/issues/4845
- [ ] https://github.com/projectdiscovery/nuclei/issues/4846
- [ ] https://github.com/projectdiscovery/nuclei/issues/4847
- [ ] https://github.com/projectdiscovery/nuclei/issues/4848
- [x] ~`fuzz-custom` field to support dynamic payloads (like incrementing existing values etc)~
- [x] Fuzzing Blog Post[s]
- [ ] https://github.com/projectdiscovery/nuclei/issues/4857
```

## Minor Changes 

```[tasklist]
### Tasks
- [x] Support multipart/form-data fuzzing in request body
- [x] Refactor and unify input modes using new interface
- [x] Integration tests using fuzzingplayground server cli
```
