### ISSUE TITLE
OpenAPI Input Format Validations

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4857]
### Please describe your feature request:
when generating requests using openapi schema file, certain validations / placeholder logic needs to be implemented for consistency and overall app behaviour

```[tasklist]
### Tasks
- [x] Allow passing openapi params + override params using `-V -var` flag
- [x] Support `-required-only` flag to only use required params when generating requests
- [x] fatal error when global auth parameters or required parameters are missing
- [x] allow skipping any and all requests[s] when required params are not available using `-skip-format-validation` flag
- [x] Fallback to default placeholder values when required params are not given and `-skip-format-validation` is used
- [x] For Ease of Use auto generate and load `required_openapi_params.yaml` config file when required parameters are not given ( in CLI Mode only)
- [x] Optional Support specifying optional parameters in `required_openapi_params.yaml` config file
```
