### ISSUE TITLE
Fuzzing additions & enhancements

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#5216]
### Please describe your feature request:

```[tasklist]
### Tasks
- [x] Add `part: request` to fuzz all the keys in request
- [x] Add `-display-fuzz-points` option to display fuzzing points (for debugging)
- [x] Add `-fuzz-aggression` option support in CLI and in Fuzzing templates
- [x] Add `-fuzz-param-frequency` option to control counter for skipping uninteresting parameter
```
