### ISSUE TITLE
Add `overwrite` field to control secret file authentication behavior

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei#5465]
### Please describe your feature request:

We'd like to add an `overwrite` field option so users can choose whether or not the secret file should override hardcoded values in templates. This will give more flexibility in how these values are handled.

### Describe the use case of this feature:

Right now, secret file authentication always overrides hardcoded values in templates by default (https://github.com/projectdiscovery/nuclei/issues/5455). This can be a bit limiting when users want to keep the original hardcoded values. By adding an `overwrite` field option, users can decide if they want the secret file to replace the hardcoded values or not. This feature will be super handy for different configurations depending on the environment or other factors, giving users more control and flexibility with their templates.
```[tasklist]
### Tasks
- [x] Avoid override secrets
- [x] Add `Overwrite` field
- [x] Update Secret File doc (`headers` key is case-sensitive)
- [x] Add `overwrite` field doc
```

**Comment by dwisiswant0** [comment]
Superseded by #5521.
